### ISSUE TITLE
Kinect libraries are not available...

### ISSUE THREAD

**Issue by jayjupdhig** [Zoomicon/SpeechLib#1]
Hi

I pulled your project via git clone to a folder then i opened the visual studio project with visual studio 2019 community edition. After clicking "build project map", i got that error:

![image](https://user-images.githubusercontent.com/42765391/151186447-4645ef45-9e17-46b3-849b-c5aa32ec6d2b.png)

Maybe somebody can explain me how to reach my goal - to complie the whole library?

thank you very much for your feedbacks. :-)

**Comment by birbilis** [comment]
Hi, do you have Kinect V1 SDK (not the V2 SDK for the redesigned 2nd-gen Kinect that came with Xbox One) installed?
try installing first the 1.8 version from here: https://www.microsoft.com/en-us/download/details.aspx?id=40278

**Comment by birbilis** [comment]
...also if you see the details in that page it has a link to Kinect Developer Toolkit (can try installing that one too maybe)

It does mention the Microsoft Speech Platform, but the link it has there is broken

However this link might be related/helpful: https://www.microsoft.com/en-us/download/details.aspx?id=34809

Let me know if you have issues. Another idea is to remove the Kinect stuff from the library if you don't need it

**Comment by jayjupdhig** [comment]
Thank you very much for your fast feedback - will look on it ASAP! :-)

**Comment by jayjupdhig** [comment]
Now it compiles all - thank you very very much!! :-)

![image](https://user-images.githubusercontent.com/42765391/151329977-c313f757-08e6-4ddb-a932-85f7241c56bd.png)

**Comment by birbilis** [comment]
In order to add some info about it at the readme of their repo, did you install just the Kinect V1 SDK or did you also install the Kinect V1 Toolkit and/or the language packs which I had mentioned as being separate links?

**Comment by kosuodhmwa** [comment]
I installed these two files, the lang pack is for german (de-DE):

![we45rt62456](https://user-images.githubusercontent.com/24782840/151365428-cd305378-e83b-4a8e-9e5c-85510059f107.jpg)

**Comment by jayjupdhig** [comment]
BTW.: When i compare (and try to adapt) the source code from with "original" SpeechRecognitionEngine class to your library...

`using System; 
using System.Globalization;
using System.Speech.Recognition;

namespace ConsoleApp1
{
    class Program
    {
        private Program(string[] args)
        {            
            this.test();
        }

        private void test()
        {
            // Create an in-process speech recognizer for the en-US locale.  
            using (
            SpeechRecognitionEngine recognizer =
              new SpeechRecognitionEngine(
                new System.Globalization.CultureInfo("de-DE")))
            {
                DictationGrammar dg = new DictationGrammar();
               
                // Create and load a dictation grammar.  
                recognizer.LoadGrammar(dg);

                // Add a handler for the speech recognized event.  
                recognizer.SpeechRecognized +=
                  new EventHandler<SpeechRecognizedEventArgs>(recognizer_SpeechRecognized);

                // Configure input to the speech recognizer.  
                recognizer.SetInputToDefaultAudioDevice();

                // Start asynchronous, continuous speech recognition.  
                recognizer.RecognizeAsync(RecognizeMode.Multiple);

                // Keep the console window open.  
                while (true)
                {
                    Console.ReadLine();
                }
            }
        }

        // Handle the SpeechRecognized event.  
        static void recognizer_SpeechRecognized(object sender, SpeechRecognizedEventArgs e)
        {
            Console.WriteLine("Recognized text: " + e.Result.Text);
        }

        static void Main(string[] args)
        {
            if(args == null)
            {
                args = new string[0];
            }
            
            new Program(args);
        }
    }
}`

...then i see that your library does not accept any contructor arguments. So i can't add any language / culture info to the instance of SpeechRecognitionKinectV1 class:

´using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Speech.Recognition;
using SpeechLib.Recognition.KinectV1;

using System.Globalization;

namespace Spechlib_Example
{
    class Program
    {
        private static DictationGrammar getDictationGrammar()
        {
            DictationGrammar dg = new DictationGrammar();
            
            return dg;
        }

        private Program(string[] args)
        {
            Console.WriteLine("TEST");

            using (
            SpeechRecognitionKinectV1 recognizer =
                new SpeechRecognitionKinectV1())
            {
                recognizer.LoadGrammar(Program.getDictationGrammar());
                recognizer.SpeechRecognitionEngine.SpeechRecognized += new EventHandler<SpeechRecognizedEventArgs>(recognizer_SpeechRecognized);
                recognizer.SetInputToDefaultAudioDevice();
                recognizer.SpeechRecognitionEngine.RecognizeAsync(RecognizeMode.Multiple);

                while (true)
                {
                    Console.ReadLine();
                }
            }                     
        }

        // Handle the SpeechRecognized event.  
        static void recognizer_SpeechRecognized(object sender, SpeechRecognizedEventArgs e)
        {
            Console.WriteLine("Recognized text: " + e.Result.Text);
        }

        public static void Main(string[] args)
        {
            new Program(args);
        }
    }
}´


Maybe you can give me a hint?

**Comment by jayjupdhig** [comment]
(source code format from GitHub with ´-character seems to be a joke... so i'm sorry!! ;-))

**Comment by jayjupdhig** [comment]
Reopened - or do i have to create a new issue for my 2nd question?

**Comment by birbilis** [comment]
yes, better copy from here to separate issue and remove the unrelated comments from above thread

**Comment by jayjupdhig** [comment]
ok thx

**Comment by birbilis** [comment]
still see the unrelated stuff in this thread, if you still have that other issue, please make a new thread and move those (copy, then delete) comments from this thread to be able to follow up easily on each issue separately

**Comment by kosuodhmwa** [comment]
The problem was: "DictationGrammar" is completely unuseable (it's a MS-related issue, you are not responsible for that. Maybe it exists just for the future?), but with pre-defined works it works not bad... i just need to write some words in a "special" way (e.g. use 2 characters on some words instead of one etc.) then it works.

But "DictationGrammar" seems to by unuseable "by default" - many search results on google confirmed that.

**Comment by birbilis** [comment]
take a look at my SpeechTurtle and TrackingCam repos, where I was using this library in case there's any hint (search for references to the related classes there).

**Comment by kosuodhmwa** [comment]
thx!! :-)

**Comment by birbilis** [comment]
just noticed I had also added speech recoginition to my fork of HotSpotizer:
https://github.com/birbilis/Hotspotizer/tree/master/Hotspotizer.WPF/Grammars

for the other two ones I mentioned see their grammars at:
https://github.com/Zoomicon/TrackingCam/tree/master/TrackingCam/Grammars
and
https://github.com/Zoomicon/SpeechTurtle/tree/master/Grammars

**Comment by jayjupdhig** [comment]
Thank you very very much. Currently, it's OK with "static" (non-dictation) Grammar - but thank you anyway, now i know what i have to use if i have a specific use case! :-)
